import type { Metadata } from "next";
import { jetBrainsMono } from "@/constants/Fonts";
import "./globals.css";
import Body from "@/components/Body";
import { ThemeContextProvider } from "./context/themeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`${jetBrainsMono.className}`}>
      <ThemeContextProvider>
        <Body>
          {children}
        </Body>
      </ThemeContextProvider>
    </html>
  );
}
